config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home', to: 'pages#home', as: :home
  get '/projects', to: 'pages#projects', as: :projects
  get '/aboutme', to: 'pages#aboutme', as: :aboutme
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def aboutme
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  <!--  <link rel="stylesheet" href="../../../assets/stylesheets/all.scss">
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/grid.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com"> -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400;700&display=swap" rel="stylesheet">
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/aboutme.html.erb
 <%= render 'shared/navbar' %>

<body class="backgro">
  <div class="container">
    <h1>hello guys</h1>
  </div>
</body>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

<body>
  <%= render 'shared/navbar' %>

  <section class="main">
    <div class="container">
    <div class="main-content">
      <h1>Hello, my name is Mark Lee. <br> Welcome to my portfolio. <br> I am a back end || Ruby on rails developer based in Berlin, Germany.
          <br>Nam rhoncus augue sit amet tortor viverra maximus. </h1>
    </div>
  </div>
  </section>

  <section class="footer">
    <div class="footer-links">
    </div>
    <div class="footer-copyright">
      This footer is for the back-end professional.
    </div>
  </section>

</body>
</html>

app/views/pages/projects.html.erb
 <%= render 'shared/navbar' %>

<div class="container">
  <section class="section" id="section--3">
  <div class="plants row">
    <div class="col-8">
      <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618410815/plants3_f58v99.png" class="plants1">
      <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618410893/plants4_u2xh72.png" class="plants1">
    </div>
    <div class="col-4">
      <h2 id="green">Plants vs Zoombies</h2>
      <br>
      <p>Plants vs Zoombies was my first project as a developer, made on the 7th week of Bootcamp. <br/> Having as a task to build an
      Airbnb clone with an open theme, our group choose Plants-vs-Zoombies characters, what was an great choice for te design of the website.
      Build in Ruby on rails the user can check offers and informations about plants of his choice and also add an offer if he has any.
      Beeing in charge for the back end, this was my first time working with rails and it couldn't be better, how dinamic, intuitive and easy to use and read
      made me fall in love with the web framework. Feel free to check the website! <button type="button" class="btn btn-success">Link</button>
      </p>
    </div>
  </div>
  </section>

  <div class="row">
    <div class=" where2 col-4">
      <h1>Where<span id="blue">2</span>live</h1>
      <p>Where2Live a safe place to find your new place. As the name and subtitle says this application helps people to get information about the area
      that they pretend to move in or to rent for a short period. The user can choose up to 6 amenityes of his preference and our app will filter which
      districts contains those choices and display it to the user. After this, the user choose a district and it displays   </p>
    </div>
    <section class="col-8">
      <div class="slider">
          <div class="slide">
            <div class="testimonial">
                <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618574937/where1_xodaze.png"/>
            </div>
          </div>

        <div class="slide">
            <div class="testimonial">
                <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618575012/where2_zonhlq.png" />
            </div>
        </div>

        <div class="slide">
            <div class="testimonial">
                <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618575017/where3_meq569.png" />
            </div>
        </div>

        <div class="slide">
            <div class="testimonial">
                <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618575022/where4_joqpfy.png" />
            </div>
        </div>

        <div class="slide">
            <div class="testimonial">
                <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618575027/where6_c89irv.png" />
            </div>
        </div>

        <div class="slide">
            <div class="testimonial">
                <img src="https://res.cloudinary.com/dftzp2fex/image/upload/v1618575057/where7_vbqrzn.png" />
            </div>
        </div>

        <button class="slider__btn slider__btn--left">&larr;</button>
        <button class="slider__btn slider__btn--right">&rarr;</button>
        <div class="dots"></div>
      </div>
    </section>

  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="header">
    <div class="container">
      <div class="main-nav">
      <img class="logo" src="https://res.cloudinary.com/dftzp2fex/image/upload/v1619793806/new-logo1_ygrxyk.jpg">
      <ul class="ul">
        <%= link_to home_path do %>
        <li>Home</li>
        <% end %>
        <%= link_to projects_path do %>
        <li>Projects</li>
        <% end %>
        <%= link_to aboutme_path do %>
        <li>About Me</li>
        <% end %>
      </ul>
      </div>
    </div>
</header>